swipe:
  3: 
    left: 
      command: 'sh /home/joshh/Documents/scripts/nextonmonitor.sh next'
    right: 
      command: 'sh /home/joshh/Documents/scripts/nextonmonitor.sh prev'
    up: 
      command: 'rofi -show drun'
    down: 
      command: 'killall rofi || xdotool key Escape'
  4:
    left: 
      command: 'xdotool key alt+Left'
    right: 
      command: 'xdotool key alt+Right'
    up: 
      command: 'loginctl lock-session'
    down: 
      command: 'i3-msg workspace 21'
pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
     command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.2
  pinch: 0.4

interval:
  swipe: 0.5
  pinch: 0.4
